// docs/.vitepress/demos/timer/06-notify.vue
<!--
  Copyright (c) 2021-Present XiHanFun and contributors.
  Licensed under the MIT License. See LICENSE in the project root for license information.
-->

<!-- 每一拍与到点 | tick 每过一个 interval 发一次，complete 只在走到终点那一刻发一次；到点那一拍不再发 tick -->
<script setup lang="ts">
import {
  XhTimerControl,
  XhTimerDisplay,
  XhTimerItem,
  XhTimerRoot,
  XhTimerSeparator,
} from "@xihan-ui/vue";
import { ref } from "vue";

const ticks = ref(0);
const done = ref(false);

// 按钮本身归组件管起停，这里只把计数一起归零
function restart(): void {
  ticks.value = 0;
  done.value = false;
}
</script>

<template>
  <XhTimerRoot
    countdown
    :start-ms="5000"
    @tick="ticks++"
    @complete="done = true"
  >
    <XhTimerDisplay>
      <XhTimerItem unit="minutes" />
      <XhTimerSeparator>:</XhTimerSeparator>
      <XhTimerItem unit="seconds" />
    </XhTimerDisplay>
    <XhTimerControl @click="restart">起停</XhTimerControl>
  </XhTimerRoot>

  <p>已经跳了 {{ ticks }} 拍{{ done ? "，到点了" : "" }}</p>
</template>

// docs/.vitepress/demos/timer/06-notify.tsx
/*
 * Copyright (c) 2021-Present XiHanFun and contributors.
 * Licensed under the MIT License. See LICENSE in the project root for license information.
 */

// 每一拍与到点 | tick 每过一个 interval 发一次，complete 只在走到终点那一刻发一次；到点那一拍不再发 tick
import type { ReactNode } from "react";
import {
  XhTimerControl,
  XhTimerDisplay,
  XhTimerItem,
  XhTimerRoot,
  XhTimerSeparator,
} from "@xihan-ui/react";
import { useState } from "react";

export default function Demo(): ReactNode {
  const [ticks, setTicks] = useState(0);
  const [done, setDone] = useState(false);

  // 按钮本身归组件管起停，这里只把计数一起归零
  function restart(): void {
    setTicks(0);
    setDone(false);
  }

  return (
    <>
      <XhTimerRoot
        countdown
        startMs={5000}
        onTick={() => setTicks(n => n + 1)}
        onComplete={() => setDone(true)}
      >
        <XhTimerDisplay>
          <XhTimerItem unit="minutes" />
          <XhTimerSeparator>:</XhTimerSeparator>
          <XhTimerItem unit="seconds" />
        </XhTimerDisplay>
        <XhTimerControl onClick={restart}>起停</XhTimerControl>
      </XhTimerRoot>

      <p>{`已经跳了 ${ticks} 拍${done ? "，到点了" : ""}`}</p>
    </>
  );
}
