// docs/.vitepress/demos/switch/06-event.tsx
/*
 * Copyright (c) 2021-Present XiHanFun and contributors.
 * Licensed under the MIT License. See LICENSE in the project root for license information.
 */

// 事件 | checked-change 带一份 { checked }，非受控时内部转移也照发一次
import type { ReactNode } from "react";
import { XhSwitch } from "@xihan-ui/react";
import { useState } from "react";

export default function Demo(): ReactNode {
  const [times, setTimes] = useState(0);
  const [last, setLast] = useState("（还没动过）");

  function onCheckedChange(details: { checked: boolean }): void {
    setTimes(n => n + 1);
    setLast(details.checked ? "开" : "关");
  }

  return (
    <>
      <XhSwitch onCheckedChange={onCheckedChange} />
      <span>{`翻转 ${times} 次 · 最近落到 ${last}`}</span>
    </>
  );
}

// docs/.vitepress/demos/switch/06-event.vue
<!--
  Copyright (c) 2021-Present XiHanFun and contributors.
  Licensed under the MIT License. See LICENSE in the project root for license information.
-->

<!-- 事件 | checked-change 带一份 { checked }，非受控时内部转移也照发一次 -->
<script setup lang="ts">
import { XhSwitch } from "@xihan-ui/vue";
import { ref } from "vue";

const times = ref(0);
const last = ref("（还没动过）");

function onCheckedChange(details: { checked: boolean }) {
  times.value += 1;
  last.value = details.checked ? "开" : "关";
}
</script>

<template>
  <XhSwitch @checked-change="onCheckedChange" />
  <span>翻转 {{ times }} 次 · 最近落到 {{ last }}</span>
</template>
