// docs/.vitepress/demos/dialog/09-service.vue
<!--
  Copyright (c) 2021-Present XiHanFun and contributors.
  Licensed under the MIT License. See LICENSE in the project root for license information.
-->

<!-- 命令式服务 | createDialogService 的 confirm 与单按钮预设：一行调用弹出，onOk 返回 Promise 时确认钮自动 pending 并拦住关闭；多次调用排队顺次弹 -->
<script setup lang="ts">
import type { DialogService } from "@xihan-ui/vue";
import { createDialogService, XhButton } from "@xihan-ui/vue";
import { onBeforeUnmount, ref } from "vue";

let modal: DialogService | undefined;
function use(): DialogService {
  modal ??= createDialogService();
  return modal;
}
onBeforeUnmount(() => modal?.dispose());

const lastAnswer = ref("（还没问过）");

async function remove(): Promise<void> {
  const ok = await use().confirm({
    title: "删除工作区",
    content: "删除后 30 天内还能恢复。",
    tone: "danger",
    okText: "删除",
    onOk: () => new Promise(r => setTimeout(r, 900)),
  });
  lastAnswer.value = ok ? "已删除" : "取消了";
}
</script>

<template>
  <div style="display: flex; flex-wrap: wrap; align-items: center; gap: 8px">
    <XhButton variant="solid" tone="danger" @click="remove()">删除工作区</XhButton>
    <XhButton
      variant="outline"
      @click="use().error({ title: '同步失败', content: '稍后重试。' })"
    >
      error 告知框
    </XhButton>
    <span>上次答复：{{ lastAnswer }}</span>
  </div>
</template>

// docs/.vitepress/demos/dialog/09-service.tsx
/*
 * Copyright (c) 2021-Present XiHanFun and contributors.
 * Licensed under the MIT License. See LICENSE in the project root for license information.
 */

// 命令式服务 | createDialogService 的 confirm 与单按钮预设：一行调用弹出，onOk 返回 Promise 时确认钮自动 pending 并拦住关闭；多次调用排队顺次弹
import type { DialogService } from "@xihan-ui/react";
import type { ReactNode } from "react";
import { createDialogService, XhButton } from "@xihan-ui/react";
import { useEffect, useRef, useState } from "react";

export default function Demo(): ReactNode {
  const modal = useRef<DialogService>(undefined);
  function use(): DialogService {
    modal.current ??= createDialogService();
    return modal.current;
  }
  useEffect(() => () => modal.current?.dispose(), []);

  const [lastAnswer, setLastAnswer] = useState("（还没问过）");

  async function remove(): Promise<void> {
    const ok = await use().confirm({
      title: "删除工作区",
      content: "删除后 30 天内还能恢复。",
      tone: "danger",
      okText: "删除",
      onOk: () => new Promise(r => setTimeout(r, 900)),
    });
    setLastAnswer(ok ? "已删除" : "取消了");
  }

  return (
    <div style={{ display: "flex", flexWrap: "wrap", alignItems: "center", gap: "8px" }}>
      <XhButton variant="solid" tone="danger" onClick={() => remove()}>删除工作区</XhButton>
      <XhButton
        variant="outline"
        onClick={() => use().error({ title: "同步失败", content: "稍后重试。" })}
      >
        error 告知框
      </XhButton>
      <span>{`上次答复：${lastAnswer}`}</span>
    </div>
  );
}
