// docs/.vitepress/demos/hotkeys/02-scoped.tsx
/*
 * Copyright (c) 2021-Present XiHanFun and contributors.
 * Licensed under the MIT License. See LICENSE in the project root for license information.
 */

// 局部范围 | 仅在指定区域内响应
import type { ReactNode } from "react";
import { XhHotkeys } from "@xihan-ui/react";
import { useRef, useState } from "react";

export default function Demo(): ReactNode {
  const [count, setCount] = useState(0);
  const scope = useRef<HTMLDivElement>(null);
  return (
    <div
      ref={scope}
      tabIndex={0}
      style={{ padding: "12px 16px", borderRadius: "var(--xh-shape-control)", background: "var(--xh-bg-subtle)" }}
    >
      {`聚焦后按 Mod + Enter · ${count ? `已触发 ${count} 次` : "等待输入"}`}
      <XhHotkeys keys={["Mod", "Enter"]} target={() => scope.current} onHotKey={() => setCount(value => value + 1)} />
    </div>
  );
}

// docs/.vitepress/demos/hotkeys/02-scoped.vue
<!--
  Copyright (c) 2021-Present XiHanFun and contributors.
  Licensed under the MIT License. See LICENSE in the project root for license information.
-->

<!-- 局部范围 | 仅在指定区域内响应 -->
<script setup lang="ts">
import { XhHotkeys } from "@xihan-ui/vue";
import { ref } from "vue";

const count = ref(0);
const scope = ref<HTMLElement | null>(null);
</script>

<template>
  <div
    ref="scope"
    tabindex="0"
    style="padding: 12px 16px; border-radius: var(--xh-shape-control); background: var(--xh-bg-subtle)"
  >
    聚焦后按 Mod + Enter · {{ count ? `已触发 ${count} 次` : "等待输入" }}
    <XhHotkeys :keys="['Mod', 'Enter']" :target="() => scope" @hot-key="count += 1" />
  </div>
</template>
