// docs/.vitepress/demos/toggle/04-variant.vue
<!-- 形态 | 设置切换按钮外观 -->
<script setup lang="ts">
import { XhToggle } from "@xihan-ui/vue";

const variants = ["solid", "subtle", "outline", "ghost"] as const;
</script>

<template>
  <XhToggle v-for="variant in variants" :key="variant" :variant="variant" default-pressed>
    {{ variant }}
  </XhToggle>
</template>

// docs/.vitepress/demos/toggle/04-variant.tsx
// 形态 | 设置切换按钮外观
import type { ReactNode } from "react";
import { XhToggle } from "@xihan-ui/react";

const variants = ["solid", "subtle", "outline", "ghost"] as const;

export default function Demo(): ReactNode {
  return (
    <>
      {variants.map(variant => (
        <XhToggle key={variant} variant={variant} defaultPressed>{variant}</XhToggle>
      ))}
    </>
  );
}
