// docs/.vitepress/demos/highlight/03-case-sensitive.vue
<!--
  Copyright (c) 2021-Present XiHanFun and contributors.
  Licensed under the MIT License. See LICENSE in the project root for license information.
-->

<!-- 区分大小写 | 缺省不区分，开了 case-sensitive 就按写法比 -->
<script setup lang="ts">
import { XhHighlight } from "@xihan-ui/vue";

const text = "XiHan UI 与 xihan ui 是同一个名字的两种写法。";
</script>

<template>
  <div style="display: flex; flex-direction: column; gap: 12px">
    <XhHighlight :text="text" keyword="ui" />
    <XhHighlight :text="text" keyword="ui" case-sensitive />
  </div>
</template>

// docs/.vitepress/demos/highlight/03-case-sensitive.tsx
/*
 * Copyright (c) 2021-Present XiHanFun and contributors.
 * Licensed under the MIT License. See LICENSE in the project root for license information.
 */

// 区分大小写 | 缺省不区分，开了 case-sensitive 就按写法比
import type { ReactNode } from "react";
import { XhHighlight } from "@xihan-ui/react";

const text = "XiHan UI 与 xihan ui 是同一个名字的两种写法。";

export default function Demo(): ReactNode {
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
      <XhHighlight text={text} keyword="ui" />
      <XhHighlight text={text} keyword="ui" caseSensitive />
    </div>
  );
}
