// docs/.vitepress/demos/scroll-area/03-orientation.tsx
// 横向滚动 | 只启用横向滚动
import type { ReactNode } from "react";
import {
  XhScrollAreaContent,
  XhScrollAreaRoot,
  XhScrollAreaScrollbar,
  XhScrollAreaThumb,
  XhScrollAreaTrack,
  XhScrollAreaViewport,
} from "@xihan-ui/react";

const cards = ["brand", "info", "success", "warning", "danger", "neutral"] as const;

export default function Demo(): ReactNode {
  return (
    <XhScrollAreaRoot
      orientation="horizontal"
      type="always"
      style={{ blockSize: "110px", inlineSize: "min(420px, 100%)", borderRadius: "var(--xh-shape-surface)" }}
    >
      <XhScrollAreaViewport>
        <XhScrollAreaContent style={{ display: "flex", gap: "10px", padding: "10px 12px" }}>
          {cards.map(tone => (
            <div
              key={tone}
              data-demo-block
              data-tone={tone}
              style={{
                flex: "none",
                inlineSize: "96px",
                blockSize: "64px",
              }}
            />
          ))}
        </XhScrollAreaContent>
      </XhScrollAreaViewport>
      <XhScrollAreaScrollbar orientation="horizontal">
        <XhScrollAreaTrack>
          <XhScrollAreaThumb />
        </XhScrollAreaTrack>
      </XhScrollAreaScrollbar>
    </XhScrollAreaRoot>
  );
}

// docs/.vitepress/demos/scroll-area/03-orientation.vue
<!-- 横向滚动 | 只启用横向滚动 -->
<script setup lang="ts">
import {
  XhScrollAreaContent,
  XhScrollAreaRoot,
  XhScrollAreaScrollbar,
  XhScrollAreaThumb,
  XhScrollAreaTrack,
  XhScrollAreaViewport,
} from "@xihan-ui/vue";

const cards = ["brand", "info", "success", "warning", "danger", "neutral"] as const;
</script>

<template>
  <XhScrollAreaRoot
    orientation="horizontal"
    type="always"
    style="block-size: 110px; inline-size: min(420px, 100%); border-radius: var(--xh-shape-surface)"
  >
    <XhScrollAreaViewport>
      <XhScrollAreaContent style="display: flex; gap: 10px; padding: 10px 12px">
        <div
          v-for="tone in cards"
          :key="tone"
          data-demo-block
          :data-tone="tone"
          style="
            flex: none;
            inline-size: 96px;
            block-size: 64px;
          "
        />
      </XhScrollAreaContent>
    </XhScrollAreaViewport>
    <XhScrollAreaScrollbar orientation="horizontal">
      <XhScrollAreaTrack>
        <XhScrollAreaThumb />
      </XhScrollAreaTrack>
    </XhScrollAreaScrollbar>
  </XhScrollAreaRoot>
</template>
