// docs/.vitepress/demos/pin-input/02-otp.vue
<!--
  Copyright (c) 2021-Present XiHanFun and contributors.
  Licensed under the MIT License. See LICENSE in the project root for license information.
-->

<!-- 一次性验证码 | otp 补上 autocomplete=one-time-code，隐藏输入把拼好的整串交给表单，填满那一刻发 value-complete -->
<script setup lang="ts">
import {
  XhPinInputHiddenInput,
  XhPinInputInput,
  XhPinInputLabel,
  XhPinInputRoot,
} from "@xihan-ui/vue";
import { ref } from "vue";

const code = ref<string[]>([]);
const submitted = ref("");
</script>

<template>
  <XhPinInputRoot
    v-model:value="code"
    :length="6"
    name="code"
    placeholder="·"
    otp
    @value-complete="submitted = $event.valueAsString"
  >
    <XhPinInputLabel>短信验证码</XhPinInputLabel>
    <div style="display: flex">
      <XhPinInputInput v-for="i in 6" :key="i" :index="i - 1" />
    </div>
    <XhPinInputHiddenInput />
  </XhPinInputRoot>
  <span>填满时拿到：{{ submitted || "（未填满）" }}</span>
</template>

// docs/.vitepress/demos/pin-input/02-otp.tsx
/*
 * Copyright (c) 2021-Present XiHanFun and contributors.
 * Licensed under the MIT License. See LICENSE in the project root for license information.
 */

// 一次性验证码 | otp 补上 autocomplete=one-time-code，隐藏输入把拼好的整串交给表单，填满那一刻发 value-complete
import type { ReactNode } from "react";
import {
  XhPinInputHiddenInput,
  XhPinInputInput,
  XhPinInputLabel,
  XhPinInputRoot,
} from "@xihan-ui/react";
import { useState } from "react";

const cells = Array.from({ length: 6 }, (_, i) => i);

export default function Demo(): ReactNode {
  const [code, setCode] = useState<string[]>([]);
  const [submitted, setSubmitted] = useState("");

  return (
    <>
      <XhPinInputRoot
        value={code}
        onValueChange={details => setCode(details.value)}
        length={6}
        name="code"
        placeholder="·"
        otp
        onValueComplete={details => setSubmitted(details.valueAsString)}
      >
        <XhPinInputLabel>短信验证码</XhPinInputLabel>
        <div style={{ display: "flex" }}>
          {cells.map(i => <XhPinInputInput key={i} index={i} />)}
        </div>
        <XhPinInputHiddenInput />
      </XhPinInputRoot>
      <span>{`填满时拿到：${submitted || "（未填满）"}`}</span>
    </>
  );
}
