// docs/.vitepress/demos/pagination/04-translations.tsx
// 读屏文案 | translations 换掉 nav 地标名与各按钮的 aria-label，默认是英文
import type { ReactNode } from "react";
import {
  XhPaginationEllipsisTrigger,
  XhPaginationItem,
  XhPaginationNextTrigger,
  XhPaginationPrevTrigger,
  XhPaginationRoot,
} from "@xihan-ui/react";

const translations = {
  root: "订单列表分页",
  prevTrigger: "上一页",
  nextTrigger: "下一页",
  item: (page: number) => `第 ${page} 页`,
};

export default function Demo(): ReactNode {
  return (
    <XhPaginationRoot
      count={80}
      pageSize={10}
      translations={translations}
      style={{ inlineSize: "100%" }}
    >
      {({ pages }) => (
        <>
          <XhPaginationPrevTrigger />
          {pages.map((p, i) => (p === "ellipsis"
            ? <XhPaginationEllipsisTrigger key={`${p}-${i}`} />
            : <XhPaginationItem key={`${p}-${i}`} value={p}>{p}</XhPaginationItem>))}
          <XhPaginationNextTrigger />
        </>
      )}
    </XhPaginationRoot>
  );
}

// docs/.vitepress/demos/pagination/04-translations.vue
<!-- 读屏文案 | translations 换掉 nav 地标名与各按钮的 aria-label，默认是英文 -->
<script setup lang="ts">
import {
  XhPaginationEllipsisTrigger,
  XhPaginationItem,
  XhPaginationNextTrigger,
  XhPaginationPrevTrigger,
  XhPaginationRoot,
} from "@xihan-ui/vue";

const translations = {
  root: "订单列表分页",
  prevTrigger: "上一页",
  nextTrigger: "下一页",
  item: (page: number) => `第 ${page} 页`,
};
</script>

<template>
  <XhPaginationRoot
    v-slot="{ pages }"
    :count="80"
    :page-size="10"
    :translations="translations"
    style="inline-size: 100%"
  >
    <XhPaginationPrevTrigger />
    <template v-for="(p, i) in pages" :key="`${p}-${i}`">
      <XhPaginationEllipsisTrigger v-if="p === 'ellipsis'" />
      <XhPaginationItem v-else :value="p">{{ p }}</XhPaginationItem>
    </template>
    <XhPaginationNextTrigger />
  </XhPaginationRoot>
</template>
