// docs/.vitepress/demos/select/10-custom-content.tsx
// 自定义内容 | 自定义选项和当前值
import type { ReactNode } from "react";
import {
  XhAvatarFallback,
  XhAvatarImage,
  XhAvatarRoot,
  XhSelectContent,
  XhSelectControl,
  XhSelectIndicator,
  XhSelectItem,
  XhSelectItemIndicator,
  XhSelectItemText,
  XhSelectLabel,
  XhSelectList,
  XhSelectPositioner,
  XhSelectRoot,
  XhSelectTrigger,
  XhSelectValueText,
} from "@xihan-ui/react";
import { useState } from "react";

const members = [
  { value: "liuyi", name: "刘一", initial: "刘", team: "设计组" },
  { value: "chener", name: "陈二", initial: "陈", team: "前端组" },
  { value: "zhangsan", name: "张三", initial: "张", team: "服务端组" },
];

export default function Demo(): ReactNode {
  const [picked, setPicked] = useState<string[]>(["liuyi"]);
  const current = members.find(m => m.value === picked[0]) ?? null;

  return (
    <XhSelectRoot
      value={picked}
      onValueChange={details => setPicked(details.value)}
      placeholder="请选择成员"
    >
      <XhSelectLabel>负责人</XhSelectLabel>
      <XhSelectControl>
        <XhSelectTrigger>
          <XhSelectValueText>
            {current
              ? (
                  <span style={{ display: "inline-flex", alignItems: "center", gap: "8px" }}>
                    <XhAvatarRoot size="sm">
                      <XhAvatarImage />
                      <XhAvatarFallback>{current.initial}</XhAvatarFallback>
                    </XhAvatarRoot>
                    {current.name}
                  </span>
                )
              : <span>请选择成员</span>}
          </XhSelectValueText>
          <XhSelectIndicator />
        </XhSelectTrigger>
      </XhSelectControl>
      <XhSelectPositioner>
        <XhSelectContent>
          <XhSelectList>
            {members.map(m => (
              <XhSelectItem key={m.value} value={m.value}>
                <XhSelectItemText>
                  <span style={{ display: "inline-flex", alignItems: "center", gap: "8px" }}>
                    <XhAvatarRoot size="sm">
                      <XhAvatarImage />
                      <XhAvatarFallback>{m.initial}</XhAvatarFallback>
                    </XhAvatarRoot>
                    <span>
                      {m.name}
                      <span style={{ color: "var(--xh-fg-muted)", fontSize: "12px" }}>{m.team}</span>
                    </span>
                  </span>
                </XhSelectItemText>
                <XhSelectItemIndicator />
              </XhSelectItem>
            ))}
          </XhSelectList>
        </XhSelectContent>
      </XhSelectPositioner>
    </XhSelectRoot>
  );
}

// docs/.vitepress/demos/select/10-custom-content.vue
<!-- 自定义内容 | 自定义选项和当前值 -->
<script setup lang="ts">
import {
  XhAvatarFallback,
  XhAvatarImage,
  XhAvatarRoot,
  XhSelectContent,
  XhSelectControl,
  XhSelectIndicator,
  XhSelectItem,
  XhSelectItemIndicator,
  XhSelectItemText,
  XhSelectLabel,
  XhSelectList,
  XhSelectPositioner,
  XhSelectRoot,
  XhSelectTrigger,
  XhSelectValueText,
} from "@xihan-ui/vue";
import { computed, ref } from "vue";

const members = [
  { value: "liuyi", name: "刘一", initial: "刘", team: "设计组" },
  { value: "chener", name: "陈二", initial: "陈", team: "前端组" },
  { value: "zhangsan", name: "张三", initial: "张", team: "服务端组" },
];

const picked = ref<string[]>(["liuyi"]);
const current = computed(() => members.find(m => m.value === picked.value[0]) ?? null);
</script>

<template>
  <XhSelectRoot v-model:value="picked" placeholder="请选择成员">
    <XhSelectLabel>负责人</XhSelectLabel>
    <XhSelectControl>
      <XhSelectTrigger>
        <XhSelectValueText>
          <span v-if="current" style="display: inline-flex; align-items: center; gap: 8px">
            <XhAvatarRoot size="sm">
              <XhAvatarImage />
              <XhAvatarFallback>{{ current.initial }}</XhAvatarFallback>
            </XhAvatarRoot>
            {{ current.name }}
          </span>
          <span v-else>请选择成员</span>
        </XhSelectValueText>
        <XhSelectIndicator />
      </XhSelectTrigger>
    </XhSelectControl>
    <XhSelectPositioner>
      <XhSelectContent>
        <XhSelectList>
          <XhSelectItem v-for="m in members" :key="m.value" :value="m.value">
            <XhSelectItemText>
              <span style="display: inline-flex; align-items: center; gap: 8px">
                <XhAvatarRoot size="sm">
                  <XhAvatarImage />
                  <XhAvatarFallback>{{ m.initial }}</XhAvatarFallback>
                </XhAvatarRoot>
                <span>
                  {{ m.name }}
                  <span style="color: var(--xh-fg-muted); font-size: 12px">{{ m.team }}</span>
                </span>
              </span>
            </XhSelectItemText>
            <XhSelectItemIndicator />
          </XhSelectItem>
        </XhSelectList>
      </XhSelectContent>
    </XhSelectPositioner>
  </XhSelectRoot>
</template>
