// docs/.vitepress/demos/dynamic-input/03-movable.vue
<!-- 换序 | movable 开了才出上下把手；挪完焦点跟着这一行走，键盘可以连按一路挪到底 -->
<script setup lang="ts">
import { ref } from "vue";
import {
  XhDynamicInputAddTrigger,
  XhDynamicInputItem,
  XhDynamicInputItemAction,
  XhDynamicInputItemContent,
  XhDynamicInputMoveDownTrigger,
  XhDynamicInputMoveUpTrigger,
  XhDynamicInputRemoveTrigger,
  XhDynamicInputRoot,
} from "@xihan-ui/vue";

const steps = ref<string[]>(["拉取代码", "安装依赖", "跑构建", "发布"]);

function setAt(index: number, next: string) {
  steps.value = steps.value.map((item, i) => (i === index ? next : item));
}
</script>

<template>
  <XhDynamicInputRoot
    v-slot="{ items }"
    v-model:value="steps"
    movable
    :create-item="() => ''"
    style="max-inline-size: 420px"
  >
    <XhDynamicInputItem v-for="row in items" :key="row.key" :index="row.index">
      <XhDynamicInputItemContent>
        <span style="inline-size: 1.5rem">{{ row.index + 1 }}.</span>
        <input
          style="inline-size: 100%"
          placeholder="这一步做什么"
          :value="row.value"
          @input="setAt(row.index, ($event.target as HTMLInputElement).value)"
        />
      </XhDynamicInputItemContent>
      <XhDynamicInputItemAction>
        <XhDynamicInputMoveUpTrigger />
        <XhDynamicInputMoveDownTrigger />
        <XhDynamicInputRemoveTrigger />
      </XhDynamicInputItemAction>
    </XhDynamicInputItem>
    <XhDynamicInputAddTrigger>+ 添加一步</XhDynamicInputAddTrigger>
    <p>顺序：{{ steps.join(" → ") }}</p>
  </XhDynamicInputRoot>
</template>

// docs/.vitepress/demos/field-array/03-movable.tsx
// 换序 | movable 开了才出上下把手；挪完焦点跟着这一行走，键盘可以连按一路挪到底
import type { ReactNode } from "react";
import {
  XhFieldArrayAddTrigger,
  XhFieldArrayItem,
  XhFieldArrayItemAction,
  XhFieldArrayItemContent,
  XhFieldArrayItemDeleteTrigger,
  XhFieldArrayMoveDownTrigger,
  XhFieldArrayMoveUpTrigger,
  XhFieldArrayRoot,
} from "@xihan-ui/react";
import { useState } from "react";

export default function Demo(): ReactNode {
  const [steps, setSteps] = useState<string[]>(["拉取代码", "安装依赖", "跑构建", "发布"]);

  function setAt(index: number, next: string): void {
    setSteps(steps.map((item, i) => (i === index ? next : item)));
  }

  return (
    <XhFieldArrayRoot
      value={steps}
      onValueChange={details => setSteps(details.value as string[])}
      movable
      createItem={() => ""}
      style={{ maxInlineSize: "420px" }}
    >
      {({ items }) => (
        <>
          {items.map(row => (
            <XhFieldArrayItem key={row.key} index={row.index}>
              <XhFieldArrayItemContent>
                <span style={{ inlineSize: "1.5rem" }}>{`${row.index + 1}.`}</span>
                <input
                  style={{ inlineSize: "100%" }}
                  placeholder="这一步做什么"
                  value={row.value as string}
                  onChange={event => setAt(row.index, event.target.value)}
                />
              </XhFieldArrayItemContent>
              <XhFieldArrayItemAction>
                <XhFieldArrayMoveUpTrigger />
                <XhFieldArrayMoveDownTrigger />
                <XhFieldArrayItemDeleteTrigger />
              </XhFieldArrayItemAction>
            </XhFieldArrayItem>
          ))}
          <XhFieldArrayAddTrigger>+ 添加一步</XhFieldArrayAddTrigger>
          <p>{`顺序：${steps.join(" → ")}`}</p>
        </>
      )}
    </XhFieldArrayRoot>
  );
}
