// docs/.vitepress/demos/text-field/08-programmatic.tsx
// 程序化改值 | setValue 直接写值，只受禁用、只读与字数上限约束；clear 执行清空意图，canClear 不成立时不做任何处理
import type { ReactNode } from "react";
import {
  XhTextFieldControl,
  XhTextFieldInput,
  XhTextFieldLabel,
  XhTextFieldRoot,
} from "@xihan-ui/react";

export default function Demo(): ReactNode {
  return (
    <XhTextFieldRoot placeholder="等着被写入" maxLength={12} clearable>
      {({ value, empty, canClear, setValue, clear }) => (
        <>
          <XhTextFieldLabel>收货人</XhTextFieldLabel>
          <XhTextFieldControl>
            <XhTextFieldInput />
          </XhTextFieldControl>
          <div style={{ display: "flex", gap: "8px" }}>
            <button type="button" onClick={() => setValue("曦寒")}>写入</button>
            <button type="button" onClick={() => setValue(`${value}·`)}>追加一个点</button>
            <button type="button" disabled={!canClear} onClick={() => clear()}>清空</button>
          </div>
          <span>{empty ? "（空）" : `${value.length} / 12`}</span>
        </>
      )}
    </XhTextFieldRoot>
  );
}

// docs/.vitepress/demos/text-field/08-programmatic.vue
<!-- 程序化改值 | setValue 直接写值，只受禁用、只读与字数上限约束；clear 执行清空意图，canClear 不成立时不做任何处理 -->
<script setup lang="ts">
import {
  XhTextFieldControl,
  XhTextFieldInput,
  XhTextFieldLabel,
  XhTextFieldRoot,
} from "@xihan-ui/vue";
</script>

<template>
  <XhTextFieldRoot
    v-slot="{ value, empty, canClear, setValue, clear }"
    placeholder="等着被写入"
    :max-length="12"
    clearable
  >
    <XhTextFieldLabel>收货人</XhTextFieldLabel>
    <XhTextFieldControl>
      <XhTextFieldInput />
    </XhTextFieldControl>
    <div style="display: flex; gap: 8px">
      <button type="button" @click="setValue('曦寒')">写入</button>
      <button type="button" @click="setValue(`${value}·`)">追加一个点</button>
      <button type="button" :disabled="!canClear" @click="clear()">清空</button>
    </div>
    <span>{{ empty ? "（空）" : `${value.length} / 12` }}</span>
  </XhTextFieldRoot>
</template>
