// docs/.vitepress/demos/text-field/16-multiline.vue
<!--
  Copyright (c) 2021-Present XiHanFun and contributors.
  Licensed under the MIT License. See LICENSE in the project root for license information.
-->

<!-- 多行与自动长高 | input 部件写成 textarea 即多行宿主；autoSize 让高度跟内容走，对象形态钉行数上下限（顶到 maxRows 后内部滚动） -->
<script setup lang="ts">
import {
  XhTextFieldControl,
  XhTextFieldInput,
  XhTextFieldLabel,
  XhTextFieldRoot,
} from "@xihan-ui/vue";
import { ref } from "vue";

const note = ref("");
</script>

<template>
  <div style="display: grid; gap: 16px; inline-size: 320px">
    <XhTextFieldRoot v-slot="{ value, atLimit }" v-model:value="note" :auto-size="{ minRows: 2, maxRows: 6 }" :max-length="120" placeholder="说点什么">
      <XhTextFieldLabel>备注（2-6 行自动长高）</XhTextFieldLabel>
      <XhTextFieldControl>
        <XhTextFieldInput as="textarea" />
      </XhTextFieldControl>
      <p style="margin: 4px 0 0; font-size: 12px" :style="{ color: atLimit ? 'var(--xh-fg-danger)' : 'var(--xh-fg-subtle)' }">
        {{ value.length }} / 120
      </p>
    </XhTextFieldRoot>

    <XhTextFieldRoot auto-size placeholder="不设行数界限，完全跟内容走">
      <XhTextFieldLabel>随写随长</XhTextFieldLabel>
      <XhTextFieldControl>
        <XhTextFieldInput as="textarea" />
      </XhTextFieldControl>
    </XhTextFieldRoot>
  </div>
</template>

// docs/.vitepress/demos/text-field/16-multiline.tsx
/*
 * Copyright (c) 2021-Present XiHanFun and contributors.
 * Licensed under the MIT License. See LICENSE in the project root for license information.
 */

// 多行与自动长高 | input 部件写成 textarea 即多行宿主；autoSize 让高度跟内容走，对象形态钉行数上下限（顶到 maxRows 后内部滚动）
import type { ReactNode } from "react";
import {
  XhTextFieldControl,
  XhTextFieldInput,
  XhTextFieldLabel,
  XhTextFieldRoot,
} from "@xihan-ui/react";
import { useState } from "react";

export default function Demo(): ReactNode {
  const [note, setNote] = useState("");

  return (
    <div style={{ display: "grid", gap: "16px", inlineSize: "320px" }}>
      <XhTextFieldRoot
        value={note}
        onValueChange={details => setNote(details.value)}
        autoSize={{ minRows: 2, maxRows: 6 }}
        maxLength={120}
        placeholder="说点什么"
      >
        {({ value, atLimit }) => (
          <>
            <XhTextFieldLabel>备注（2-6 行自动长高）</XhTextFieldLabel>
            <XhTextFieldControl>
              <XhTextFieldInput as="textarea" />
            </XhTextFieldControl>
            <p style={{ margin: "4px 0 0", fontSize: "12px", color: atLimit ? "var(--xh-fg-danger)" : "var(--xh-fg-subtle)" }}>
              {`${value.length} / 120`}
            </p>
          </>
        )}
      </XhTextFieldRoot>

      <XhTextFieldRoot autoSize placeholder="不设行数界限，完全跟内容走">
        <XhTextFieldLabel>随写随长</XhTextFieldLabel>
        <XhTextFieldControl>
          <XhTextFieldInput as="textarea" />
        </XhTextFieldControl>
      </XhTextFieldRoot>
    </div>
  );
}
